namespace Navigator.Abstractions.Pipelines.Steps;

public interface IActionResolutionPipelineStepAfter<T> : IActionResolutionPipelineStep;

public interface IActionResolutionPipelineStepAfter : IActionResolutionPipelineStepAfter<IActionResolutionPipelineStep>;