namespace Navigator.Abstractions.Pipelines.Steps;

public interface IActionExecutionPipelineStepAfter<T> : IActionExecutionPipelineStep;

public interface IActionExecutionPipelineStepAfter : IActionExecutionPipelineStepAfter<IActionExecutionPipelineStep>;